[project]
name = "laboratorio-9"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=5.5.0",
    "polars>=1.15.0",
    "streamlit>=1.40.2",
]
